%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_Directory
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_DIRECTORY_HRL).
-define(COSFILETRANSFER_DIRECTORY_HRL, true).




-endif.


