%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_OrberIFR
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ORBERIFR_HRL).
-define(OE_ORBERIFR_HRL, true).




-endif.


