%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_SequenceProxyPullSupplier
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLSUPPLIER_HRL).
-define(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLSUPPLIER_HRL, true).




-endif.


