%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyFilter
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYFILTER_HRL).
-define(OE_COSNOTIFYFILTER_HRL, true).




-endif.


