%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTime
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIME_HRL).
-define(OE_COSTIME_HRL, true).




-endif.


