%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: TimeBase
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(TIMEBASE_HRL).
-define(TIMEBASE_HRL, true).


-record('TimeBase_UtcT', {time, inacclo, inacchi, tdf}).
-record('TimeBase_IntervalT', {lower_bound, upper_bound}).


-endif.


