%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Control
%% Source: /net/isildur/ldisk/daily_build/r15b_prebuild_opu_o.2011-12-14_11/otp_src_R15B/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.29
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_CONTROL_HRL).
-define(COSTRANSACTIONS_CONTROL_HRL, true).




-endif.


